# Base container
FROM rocker/ml-gpu:3.6.1


#### Japanized ################################################################
# Change environment to Japanese (Character and DateTime)
ENV LANG ja_JP.UTF-8
ENV LC_ALL ja_JP.UTF-8
RUN sed -i '$d' /etc/locale.gen \
  && echo "ja_JP.UTF-8 UTF-8" >> /etc/locale.gen \
	&& locale-gen ja_JP.UTF-8 \
	&& /usr/sbin/update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
RUN /bin/bash -c "source /etc/default/locale"
RUN ln -sf  /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# Install ipaex and noto fonts
RUN apt-get update && apt-get install -y \
  fonts-ipaexfont fonts-noto-cjk


### Libraries for R packages ##################################################
# Install OS libraries (for R packages)
#     https://demo.rstudiopm.com/client/#/
RUN apt-get update -qq && apt-get install -y \
  imagemagick libcurl4-openssl-dev libfreetype6-dev libgl1-mesa-dev \
  libglu1-mesa-dev libgmp3-dev libjpeg-dev libmagick++-dev libopenmpi2 \
  libopenmpi-dev libpng-dev libpoppler-cpp-dev libpoppler-glib-dev \
  libtcl8.6 zlib1g-dev \
  pandoc-citeproc pandoc \
  tcl8.6-dev tcl-dev tk8.6-dev tk-dev tcllib tklib \
  poppler-utils


### Java ######################################################################
# Get and Setup Java for R
# RUN apt-get update -qq && \
#   apt-get -y --no-install-recommends install \
#   cmake \
#   default-jdk \
#   default-jre \
#   && R CMD javareconf


### R packages for modeling ###################################################
# Install R packages for Machine Learning with R (alphanureric order) and others
# for Machine Learning with R
RUN install2.r --error --skipinstalled --repos https://cloud.r-project.org \
  adabag arules C50 caret class data.table doParallel e1071 ff ffbase foreach \
  gmodels httr igraph ipred irr kernlab neuralnet psych randomForest \
  RCurl rio rjson ROCR RODBC rpart rpart.plot rvest RWeka \
  snow SnowballC tm vcd wordcloud XML xml2

# for model and infer process
RUN install2.r --error --skipinstalled --repos https://cloud.r-project.org \
  car coefplot FNN iBreakDown kknn klaR MLmetrics olsrr ranger

# tidymodels
# RUN install2.r --error --skipinstalled --repos https://cloud.r-project.org \
#   broom cli crayon dials dplyr ggplot2 infer magrittr parsnip pillar \
#   purrr recipes rlang rsample rstudioapi tibble tidypredict yardstick

RUN install2.r --skipinstalled --repos https://cloud.r-project.org \
  tidymodels

#### Other packages ###########################################################
# Other Packages
RUN install2.r --error --skipinstalled --repos https://cloud.r-project.org \
  BiocManager DiagrammeR DT ggparty ggrepel GGally learnr pdftools prettydoc \
  profvis rmdformats skimr summarytools

# `modeest` package needs Bioc package
RUN Rscript -e "BiocManager::install(c('genefilter'))" \
  && install2.r --error --skipinstalled --repos https://cloud.r-project.org \
    modeest \
  && rm -rf /tmp/downloaded_packages/ /tmp/*.rds


### blogdown for hugo blog ####################################################
# blogdown
RUN install2.r --error --skipinstalled --repos https://cloud.r-project.org \
  blogdown

RUN Rscript -e "blogdown::install_hugo()"


### GitHub packages ###########################################################
# install package from GitHub
# RUN installGithub.r k-metrics/ggbiplot
RUN Rscript -e "devtools::install_github('k-metrics/ggbiplot', \
                                         build_opts = c('--no-resave-data', \
                                         '--no-manual'))"

# C50 package has bugs to plot tree, so to install development version
# on GitHub fixes these bugs
# RUN Rscript -e "devtools::install_github('topepo/C5.0')"
RUN installGithub.r topepo/C5.0
