FROM kmetrics/tidymodels:latest

RUN install2.r --error --skipinstalled --repos https://cloud.r-project.org \
  blogdown

RUN Rscript -e "blogdown::install_hugo()"

# C50 package has bugs to plot tree, so to install development version
# on GitHub fixes these bugs
RUN Rscript -e "devtools::install_github('topepo/C5.0')"